//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.05 at 06:53:07 PM WEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.documentsuploader.soap.ti.com/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ti.soap.documentsuploader.courses;
