//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.11 at 10:02:29 PM WEST 
//


package com.ti.soap.documentsuploader.documents;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ti.soap.documentsuploader.documents package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ti.soap.documentsuploader.documents
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDocumentDetailsRequest }
     * 
     */
    public GetDocumentDetailsRequest createGetDocumentDetailsRequest() {
        return new GetDocumentDetailsRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsResponse }
     * 
     */
    public GetDocumentDetailsResponse createGetDocumentDetailsResponse() {
        return new GetDocumentDetailsResponse();
    }

    /**
     * Create an instance of {@link DocumentDetails }
     * 
     */
    public DocumentDetails createDocumentDetails() {
        return new DocumentDetails();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByNameRequest }
     * 
     */
    public GetDocumentDetailsByNameRequest createGetDocumentDetailsByNameRequest() {
        return new GetDocumentDetailsByNameRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByNameResponse }
     * 
     */
    public GetDocumentDetailsByNameResponse createGetDocumentDetailsByNameResponse() {
        return new GetDocumentDetailsByNameResponse();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByAuthorRequest }
     * 
     */
    public GetDocumentDetailsByAuthorRequest createGetDocumentDetailsByAuthorRequest() {
        return new GetDocumentDetailsByAuthorRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByAuthorResponse }
     * 
     */
    public GetDocumentDetailsByAuthorResponse createGetDocumentDetailsByAuthorResponse() {
        return new GetDocumentDetailsByAuthorResponse();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByLocationRequest }
     * 
     */
    public GetDocumentDetailsByLocationRequest createGetDocumentDetailsByLocationRequest() {
        return new GetDocumentDetailsByLocationRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByLocationResponse }
     * 
     */
    public GetDocumentDetailsByLocationResponse createGetDocumentDetailsByLocationResponse() {
        return new GetDocumentDetailsByLocationResponse();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByPublisherRequest }
     * 
     */
    public GetDocumentDetailsByPublisherRequest createGetDocumentDetailsByPublisherRequest() {
        return new GetDocumentDetailsByPublisherRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByPublisherResponse }
     * 
     */
    public GetDocumentDetailsByPublisherResponse createGetDocumentDetailsByPublisherResponse() {
        return new GetDocumentDetailsByPublisherResponse();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByUserIdRequest }
     * 
     */
    public GetDocumentDetailsByUserIdRequest createGetDocumentDetailsByUserIdRequest() {
        return new GetDocumentDetailsByUserIdRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByUserIdResponse }
     * 
     */
    public GetDocumentDetailsByUserIdResponse createGetDocumentDetailsByUserIdResponse() {
        return new GetDocumentDetailsByUserIdResponse();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByTypeIdRequest }
     * 
     */
    public GetDocumentDetailsByTypeIdRequest createGetDocumentDetailsByTypeIdRequest() {
        return new GetDocumentDetailsByTypeIdRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsByTypeIdResponse }
     * 
     */
    public GetDocumentDetailsByTypeIdResponse createGetDocumentDetailsByTypeIdResponse() {
        return new GetDocumentDetailsByTypeIdResponse();
    }

    /**
     * Create an instance of {@link GetAllDocumentsDetailsRequest }
     * 
     */
    public GetAllDocumentsDetailsRequest createGetAllDocumentsDetailsRequest() {
        return new GetAllDocumentsDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllDocumentsDetailsResponse }
     * 
     */
    public GetAllDocumentsDetailsResponse createGetAllDocumentsDetailsResponse() {
        return new GetAllDocumentsDetailsResponse();
    }

    /**
     * Create an instance of {@link CreateDocumentDetailsRequest }
     * 
     */
    public CreateDocumentDetailsRequest createCreateDocumentDetailsRequest() {
        return new CreateDocumentDetailsRequest();
    }

    /**
     * Create an instance of {@link CreateDocumentDetailsResponse }
     * 
     */
    public CreateDocumentDetailsResponse createCreateDocumentDetailsResponse() {
        return new CreateDocumentDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateDocumentDetailsRequest }
     * 
     */
    public UpdateDocumentDetailsRequest createUpdateDocumentDetailsRequest() {
        return new UpdateDocumentDetailsRequest();
    }

    /**
     * Create an instance of {@link UpdateDocumentDetailsResponse }
     * 
     */
    public UpdateDocumentDetailsResponse createUpdateDocumentDetailsResponse() {
        return new UpdateDocumentDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteDocumentDetailsRequest }
     * 
     */
    public DeleteDocumentDetailsRequest createDeleteDocumentDetailsRequest() {
        return new DeleteDocumentDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteDocumentDetailsResponse }
     * 
     */
    public DeleteDocumentDetailsResponse createDeleteDocumentDetailsResponse() {
        return new DeleteDocumentDetailsResponse();
    }

    /**
     * Create an instance of {@link GetDocumentTypeDetailsRequest }
     * 
     */
    public GetDocumentTypeDetailsRequest createGetDocumentTypeDetailsRequest() {
        return new GetDocumentTypeDetailsRequest();
    }

    /**
     * Create an instance of {@link GetDocumentTypeDetailsResponse }
     * 
     */
    public GetDocumentTypeDetailsResponse createGetDocumentTypeDetailsResponse() {
        return new GetDocumentTypeDetailsResponse();
    }

    /**
     * Create an instance of {@link DocumentTypeDetails }
     * 
     */
    public DocumentTypeDetails createDocumentTypeDetails() {
        return new DocumentTypeDetails();
    }

    /**
     * Create an instance of {@link GetAllDocumentTypesDetailsRequest }
     * 
     */
    public GetAllDocumentTypesDetailsRequest createGetAllDocumentTypesDetailsRequest() {
        return new GetAllDocumentTypesDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllDocumentTypesDetailsResponse }
     * 
     */
    public GetAllDocumentTypesDetailsResponse createGetAllDocumentTypesDetailsResponse() {
        return new GetAllDocumentTypesDetailsResponse();
    }

    /**
     * Create an instance of {@link CreateDocumentTypeDetailsRequest }
     * 
     */
    public CreateDocumentTypeDetailsRequest createCreateDocumentTypeDetailsRequest() {
        return new CreateDocumentTypeDetailsRequest();
    }

    /**
     * Create an instance of {@link CreateDocumentTypeDetailsResponse }
     * 
     */
    public CreateDocumentTypeDetailsResponse createCreateDocumentTypeDetailsResponse() {
        return new CreateDocumentTypeDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateDocumentTypeDetailsRequest }
     * 
     */
    public UpdateDocumentTypeDetailsRequest createUpdateDocumentTypeDetailsRequest() {
        return new UpdateDocumentTypeDetailsRequest();
    }

    /**
     * Create an instance of {@link UpdateDocumentTypeDetailsResponse }
     * 
     */
    public UpdateDocumentTypeDetailsResponse createUpdateDocumentTypeDetailsResponse() {
        return new UpdateDocumentTypeDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteDocumentTypeDetailsRequest }
     * 
     */
    public DeleteDocumentTypeDetailsRequest createDeleteDocumentTypeDetailsRequest() {
        return new DeleteDocumentTypeDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteDocumentTypeDetailsResponse }
     * 
     */
    public DeleteDocumentTypeDetailsResponse createDeleteDocumentTypeDetailsResponse() {
        return new DeleteDocumentTypeDetailsResponse();
    }

    /**
     * Create an instance of {@link GetUserDetailsRequest }
     * 
     */
    public GetUserDetailsRequest createGetUserDetailsRequest() {
        return new GetUserDetailsRequest();
    }

    /**
     * Create an instance of {@link GetUserDetailsResponse }
     * 
     */
    public GetUserDetailsResponse createGetUserDetailsResponse() {
        return new GetUserDetailsResponse();
    }

    /**
     * Create an instance of {@link UserDetails }
     * 
     */
    public UserDetails createUserDetails() {
        return new UserDetails();
    }

    /**
     * Create an instance of {@link GetAllUsersDetailsRequest }
     * 
     */
    public GetAllUsersDetailsRequest createGetAllUsersDetailsRequest() {
        return new GetAllUsersDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllUsersDetailsResponse }
     * 
     */
    public GetAllUsersDetailsResponse createGetAllUsersDetailsResponse() {
        return new GetAllUsersDetailsResponse();
    }

    /**
     * Create an instance of {@link CreateUserDetailsRequest }
     * 
     */
    public CreateUserDetailsRequest createCreateUserDetailsRequest() {
        return new CreateUserDetailsRequest();
    }

    /**
     * Create an instance of {@link CreateUserDetailsResponse }
     * 
     */
    public CreateUserDetailsResponse createCreateUserDetailsResponse() {
        return new CreateUserDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateUserDetailsRequest }
     * 
     */
    public UpdateUserDetailsRequest createUpdateUserDetailsRequest() {
        return new UpdateUserDetailsRequest();
    }

    /**
     * Create an instance of {@link UpdateUserDetailsResponse }
     * 
     */
    public UpdateUserDetailsResponse createUpdateUserDetailsResponse() {
        return new UpdateUserDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteUserDetailsRequest }
     * 
     */
    public DeleteUserDetailsRequest createDeleteUserDetailsRequest() {
        return new DeleteUserDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteUserDetailsResponse }
     * 
     */
    public DeleteUserDetailsResponse createDeleteUserDetailsResponse() {
        return new DeleteUserDetailsResponse();
    }

}
