//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.10 at 03:13:43 PM WEST 
//


package com.ti.soap.documentsuploader.documents;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ti.soap.documentsuploader.documents package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ti.soap.documentsuploader.documents
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDocumentDetailsRequest }
     * 
     */
    public GetDocumentDetailsRequest createGetDocumentDetailsRequest() {
        return new GetDocumentDetailsRequest();
    }

    /**
     * Create an instance of {@link GetDocumentDetailsResponse }
     * 
     */
    public GetDocumentDetailsResponse createGetDocumentDetailsResponse() {
        return new GetDocumentDetailsResponse();
    }

    /**
     * Create an instance of {@link DocumentDetails }
     * 
     */
    public DocumentDetails createDocumentDetails() {
        return new DocumentDetails();
    }

    /**
     * Create an instance of {@link GetAllDocumentsDetailsRequest }
     * 
     */
    public GetAllDocumentsDetailsRequest createGetAllDocumentsDetailsRequest() {
        return new GetAllDocumentsDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllDocumentsDetailsResponse }
     * 
     */
    public GetAllDocumentsDetailsResponse createGetAllDocumentsDetailsResponse() {
        return new GetAllDocumentsDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteDocumentDetailsRequest }
     * 
     */
    public DeleteDocumentDetailsRequest createDeleteDocumentDetailsRequest() {
        return new DeleteDocumentDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteDocumentDetailsResponse }
     * 
     */
    public DeleteDocumentDetailsResponse createDeleteDocumentDetailsResponse() {
        return new DeleteDocumentDetailsResponse();
    }

}
